// Workspace HQ country → BCP-47 locale tag for date/number formatting.
// Used by surfaces that must format by workspace context rather than the
// browser's `navigator.language` (e.g. the "Last sync" timestamp).
export const COUNTRY_LOCALE: Record<string, string> = {
  US: "en-US", GB: "en-GB", CA: "en-CA", AU: "en-AU", NZ: "en-NZ",
  IE: "en-IE", IN: "en-IN", SG: "en-SG", HK: "en-HK", ZA: "en-ZA",
  DE: "de-DE", FR: "fr-FR", ES: "es-ES", IT: "it-IT", NL: "nl-NL",
  BE: "nl-BE", AT: "de-AT", PT: "pt-PT", FI: "fi-FI", GR: "el-GR",
  LU: "fr-LU", JP: "ja-JP", CN: "zh-CN", KR: "ko-KR", BR: "pt-BR",
  MX: "es-MX", AE: "ar-AE", SA: "ar-SA", SE: "sv-SE", NO: "nb-NO",
  DK: "da-DK", CH: "de-CH", PL: "pl-PL", IL: "he-IL", TR: "tr-TR",
  TW: "zh-TW", TH: "th-TH", PH: "en-PH", MY: "ms-MY", ID: "id-ID",
  VN: "vi-VN", CL: "es-CL", CO: "es-CO", AR: "es-AR", NG: "en-NG",
  KE: "en-KE", EG: "ar-EG", PK: "en-PK",
};

export const COUNTRY_CURRENCY: Record<string, string> = {
  US: "USD", GB: "GBP", DE: "EUR", FR: "EUR", ES: "EUR", IT: "EUR", NL: "EUR",
  BE: "EUR", AT: "EUR", IE: "EUR", PT: "EUR", FI: "EUR", GR: "EUR", LU: "EUR",
  CA: "CAD", AU: "AUD", NZ: "NZD", JP: "JPY", CN: "CNY", IN: "INR",
  SG: "SGD", AE: "AED", SA: "SAR", BR: "BRL", MX: "MXN", KR: "KRW",
  SE: "SEK", NO: "NOK", DK: "DKK", CH: "CHF", PL: "PLN", ZA: "ZAR",
  IL: "ILS", TR: "TRY", HK: "HKD", TW: "TWD", TH: "THB", PH: "PHP",
  MY: "MYR", ID: "IDR", VN: "VND", CL: "CLP", CO: "COP", AR: "ARS",
  NG: "NGN", KE: "KES", EG: "EGP", PK: "PKR",
};

export const COUNTRIES = [
  { code: "US", name: "United States" },
  { code: "GB", name: "United Kingdom" },
  { code: "CA", name: "Canada" },
  { code: "AU", name: "Australia" },
  { code: "DE", name: "Germany" },
  { code: "FR", name: "France" },
  { code: "NL", name: "Netherlands" },
  { code: "IE", name: "Ireland" },
  { code: "ES", name: "Spain" },
  { code: "IT", name: "Italy" },
  { code: "SE", name: "Sweden" },
  { code: "NO", name: "Norway" },
  { code: "DK", name: "Denmark" },
  { code: "FI", name: "Finland" },
  { code: "CH", name: "Switzerland" },
  { code: "AT", name: "Austria" },
  { code: "BE", name: "Belgium" },
  { code: "PT", name: "Portugal" },
  { code: "GR", name: "Greece" },
  { code: "LU", name: "Luxembourg" },
  { code: "PL", name: "Poland" },
  { code: "IN", name: "India" },
  { code: "JP", name: "Japan" },
  { code: "CN", name: "China" },
  { code: "KR", name: "South Korea" },
  { code: "SG", name: "Singapore" },
  { code: "HK", name: "Hong Kong" },
  { code: "TW", name: "Taiwan" },
  { code: "AE", name: "United Arab Emirates" },
  { code: "SA", name: "Saudi Arabia" },
  { code: "IL", name: "Israel" },
  { code: "TR", name: "Turkey" },
  { code: "BR", name: "Brazil" },
  { code: "MX", name: "Mexico" },
  { code: "AR", name: "Argentina" },
  { code: "CL", name: "Chile" },
  { code: "CO", name: "Colombia" },
  { code: "ZA", name: "South Africa" },
  { code: "NG", name: "Nigeria" },
  { code: "KE", name: "Kenya" },
  { code: "EG", name: "Egypt" },
  { code: "NZ", name: "New Zealand" },
  { code: "TH", name: "Thailand" },
  { code: "PH", name: "Philippines" },
  { code: "MY", name: "Malaysia" },
  { code: "ID", name: "Indonesia" },
  { code: "VN", name: "Vietnam" },
  { code: "PK", name: "Pakistan" },
] as const;
