-- ============================================================================
-- 0000_ai_gads_guardrails: Initial schema baseline (all tables)
--
-- This is the full-schema bootstrap migration generated by drizzle-kit from
-- the complete schema at project initialisation.  It includes all tables that
-- pre-date task #159 AS WELL AS the task #159 additions:
--   · organizations.ai_max_lookback_days (per-org AI lookback cap)
--   · organizations.ai_daily_row_cap     (per-org AI daily row budget)
--   · ai_gads_daily_usage table          (daily usage counter; non-unique idx)
--
-- The non-unique index on ai_gads_daily_usage is corrected to a UNIQUE INDEX
-- in migration 0001_ai_gads_guardrails_fix (required for ON CONFLICT upsert).
--
-- NOTE: This project uses `drizzle-kit push` for day-to-day schema sync.
-- This file applies to fresh environments only.
-- ============================================================================
CREATE TABLE "conversations" (
        "id" serial PRIMARY KEY NOT NULL,
        "organization_id" integer,
        "user_id" integer,
        "title" text NOT NULL,
        "created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "messages" (
        "id" serial PRIMARY KEY NOT NULL,
        "conversation_id" integer NOT NULL,
        "role" text NOT NULL,
        "content" text NOT NULL,
        "created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "platform_connections" (
        "id" serial PRIMARY KEY NOT NULL,
        "organization_id" integer,
        "platform" text NOT NULL,
        "display_name" text NOT NULL,
        "credentials" jsonb NOT NULL,
        "is_active" boolean DEFAULT true NOT NULL,
        "created_at" timestamp with time zone DEFAULT now() NOT NULL,
        "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "state_snapshots" (
        "id" serial PRIMARY KEY NOT NULL,
        "conversation_id" integer NOT NULL,
        "platform" text NOT NULL,
        "platform_label" text NOT NULL,
        "tool_name" text NOT NULL,
        "tool_display_name" text NOT NULL,
        "tool_args" jsonb NOT NULL,
        "snapshot_data" jsonb,
        "display_diff" jsonb,
        "reasoning" text,
        "opportunity_cost" text,
        "status" text DEFAULT 'pending' NOT NULL,
        "execution_result" jsonb,
        "created_at" timestamp with time zone DEFAULT now() NOT NULL,
        "resolved_at" timestamp with time zone,
        "source_alert_id" text
);
--> statement-breakpoint
CREATE TABLE "audit_logs" (
        "id" serial PRIMARY KEY NOT NULL,
        "organization_id" integer,
        "conversation_id" integer,
        "snapshot_id" integer,
        "platform" text NOT NULL,
        "platform_label" text NOT NULL,
        "tool_name" text NOT NULL,
        "tool_display_name" text NOT NULL,
        "tool_args" jsonb NOT NULL,
        "display_diff" jsonb,
        "result" jsonb,
        "status" text NOT NULL,
        "created_at" timestamp with time zone DEFAULT now() NOT NULL,
        "insight_id" text
);
--> statement-breakpoint
CREATE TABLE "product_quality_fixes" (
        "id" text PRIMARY KEY NOT NULL,
        "tenant_id" text DEFAULT 'default' NOT NULL,
        "product_id" text NOT NULL,
        "sku" text DEFAULT '' NOT NULL,
        "status" text DEFAULT 'ok' NOT NULL,
        "error_code" text,
        "error_message" text,
        "plugins_fired" jsonb DEFAULT '[]'::jsonb NOT NULL,
        "changed_fields" jsonb DEFAULT '[]'::jsonb NOT NULL,
        "change_count" integer DEFAULT 0 NOT NULL,
        "optimized_product" jsonb DEFAULT 'null'::jsonb,
        "product_synced_at" timestamp with time zone NOT NULL,
        "scanned_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "warehouse_crm_leads" (
        "id" text PRIMARY KEY NOT NULL,
        "tenant_id" text DEFAULT 'default' NOT NULL,
        "crm_provider" text NOT NULL,
        "crm_lead_id" text NOT NULL,
        "email" text DEFAULT '',
        "first_name" text DEFAULT '',
        "last_name" text DEFAULT '',
        "company" text DEFAULT '',
        "lead_status" text DEFAULT 'new',
        "lifecycle_stage" text DEFAULT 'lead',
        "source" text DEFAULT '',
        "utm_source" text DEFAULT '',
        "utm_medium" text DEFAULT '',
        "utm_campaign" text DEFAULT '',
        "gclid" text DEFAULT '',
        "fbclid" text DEFAULT '',
        "conversion_value" double precision DEFAULT 0,
        "converted_at" timestamp with time zone,
        "closed_at" timestamp with time zone,
        "deal_amount" double precision DEFAULT 0,
        "deal_name" text DEFAULT '',
        "probability" double precision DEFAULT 0,
        "pipeline_stage" text DEFAULT 'discovery',
        "synced_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "warehouse_cross_platform_mapping" (
        "id" text PRIMARY KEY NOT NULL,
        "tenant_id" text DEFAULT 'default' NOT NULL,
        "google_ad_id" text NOT NULL,
        "shopify_product_id" text NOT NULL,
        "sku" text DEFAULT '',
        "final_url" text DEFAULT '',
        "match_type" text DEFAULT 'handle',
        "confidence" text DEFAULT 'HIGH',
        "synced_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "warehouse_google_ads" (
        "id" text PRIMARY KEY NOT NULL,
        "tenant_id" text DEFAULT 'default' NOT NULL,
        "campaign_id" text NOT NULL,
        "campaign_name" text DEFAULT '',
        "ad_group_id" text NOT NULL,
        "ad_group_name" text DEFAULT '',
        "ad_id" text NOT NULL,
        "final_url" text DEFAULT '',
        "cost_usd" double precision DEFAULT 0,
        "conversion_value" double precision DEFAULT 0,
        "conversions" double precision DEFAULT 0,
        "impressions" integer DEFAULT 0,
        "clicks" integer DEFAULT 0,
        "status" text DEFAULT 'ENABLED',
        "account_currency" text DEFAULT 'USD',
        "advertising_channel_type" text DEFAULT 'SEARCH',
        "synced_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "warehouse_google_ads_asset_groups" (
        "id" text PRIMARY KEY NOT NULL,
        "tenant_id" text DEFAULT 'default' NOT NULL,
        "campaign_id" text NOT NULL,
        "campaign_name" text DEFAULT '',
        "asset_group_id" text NOT NULL,
        "asset_group_name" text DEFAULT '',
        "final_urls" jsonb DEFAULT '[]'::jsonb,
        "status" text DEFAULT 'ENABLED',
        "cost_usd" double precision DEFAULT 0,
        "conversion_value" double precision DEFAULT 0,
        "conversions" double precision DEFAULT 0,
        "impressions" integer DEFAULT 0,
        "clicks" integer DEFAULT 0,
        "account_currency" text DEFAULT 'USD',
        "synced_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "warehouse_shopify_products" (
        "id" text PRIMARY KEY NOT NULL,
        "tenant_id" text DEFAULT 'default' NOT NULL,
        "product_id" text NOT NULL,
        "sku" text DEFAULT '' NOT NULL,
        "handle" text DEFAULT '' NOT NULL,
        "title" text DEFAULT '' NOT NULL,
        "variant_title" text DEFAULT '',
        "status" text DEFAULT 'active',
        "inventory_qty" integer DEFAULT 0,
        "price" double precision DEFAULT 0,
        "cogs" double precision DEFAULT 0,
        "image_url" text DEFAULT '',
        "brand_logo_url" text DEFAULT '',
        "description" text DEFAULT '',
        "llm_attributes" jsonb DEFAULT 'null'::jsonb,
        "llm_enriched_at" timestamp with time zone,
        "synced_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "team_members" (
        "id" serial PRIMARY KEY NOT NULL,
        "organization_id" integer,
        "workspace_id" integer,
        "name" text NOT NULL,
        "email" text NOT NULL,
        "role" text DEFAULT 'analyst' NOT NULL,
        "invite_code" text NOT NULL,
        "is_active" boolean DEFAULT true NOT NULL,
        "has_completed_tour" boolean DEFAULT false NOT NULL,
        "agency_setup_complete" boolean DEFAULT false NOT NULL,
        "invite_pending" boolean DEFAULT false NOT NULL,
        "created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "campaign_targets" (
        "id" serial PRIMARY KEY NOT NULL,
        "organization_id" integer NOT NULL,
        "campaign_id" text NOT NULL,
        "target_roas" double precision NOT NULL,
        "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "organizations" (
        "id" serial PRIMARY KEY NOT NULL,
        "name" text NOT NULL,
        "slug" text NOT NULL,
        "subscription_tier" text DEFAULT 'free' NOT NULL,
        "stripe_customer_id" text,
        "stripe_subscription_id" text,
        "ai_creative_credits" integer DEFAULT 0 NOT NULL,
        "primary_goal" text,
        "selected_platforms" jsonb DEFAULT '[]'::jsonb NOT NULL,
        "selected_workflows" jsonb DEFAULT '[]'::jsonb NOT NULL,
        "cogs_pct_default" double precision,
        "target_roas_default" double precision,
        "ai_max_lookback_days" integer,
        "ai_daily_row_cap" integer,
        "created_at" timestamp with time zone DEFAULT now() NOT NULL,
        CONSTRAINT "organizations_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "workspaces" (
        "id" serial PRIMARY KEY NOT NULL,
        "organization_id" integer NOT NULL,
        "client_name" text NOT NULL,
        "slug" text NOT NULL,
        "primary_goal" text,
        "enabled_integrations" jsonb DEFAULT '[]'::jsonb NOT NULL,
        "selected_workflows" jsonb,
        "invite_token" text NOT NULL,
        "status" text DEFAULT 'active' NOT NULL,
        "notes" text,
        "webhook_url" text,
        "website_url" text,
        "discovery_source" text,
        "headquarters_country" text,
        "billing_threshold" integer DEFAULT 5000,
        "created_at" timestamp with time zone DEFAULT now() NOT NULL,
        CONSTRAINT "workspaces_slug_unique" UNIQUE("slug"),
        CONSTRAINT "workspaces_invite_token_unique" UNIQUE("invite_token")
);
--> statement-breakpoint
CREATE TABLE "execution_logs" (
        "id" serial PRIMARY KEY NOT NULL,
        "workspace_id" integer,
        "user_id" text,
        "action_type" text NOT NULL,
        "snapshot_id" integer,
        "api_endpoint" text NOT NULL,
        "forward_payload" jsonb NOT NULL,
        "revert_payload" jsonb,
        "status" text DEFAULT 'executed' NOT NULL,
        "created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "live_triage_alerts" (
        "id" serial PRIMARY KEY NOT NULL,
        "workspace_id" text DEFAULT 'default' NOT NULL,
        "severity" text DEFAULT 'info' NOT NULL,
        "type" text DEFAULT 'Budget' NOT NULL,
        "title" text NOT NULL,
        "message" text NOT NULL,
        "platform" text DEFAULT '',
        "action" text DEFAULT '',
        "resolved_status" boolean DEFAULT false NOT NULL,
        "context_tag" text DEFAULT 'active',
        "snoozed_until" timestamp with time zone,
        "external_id" text DEFAULT '',
        "created_at" timestamp with time zone DEFAULT now() NOT NULL,
        "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "feed_enrichment_jobs" (
        "id" serial PRIMARY KEY NOT NULL,
        "organization_id" integer NOT NULL,
        "workspace_id" integer,
        "status" text DEFAULT 'pending' NOT NULL,
        "total_skus" integer DEFAULT 0 NOT NULL,
        "processed_skus" integer DEFAULT 0 NOT NULL,
        "failed_skus" integer DEFAULT 0 NOT NULL,
        "error_message" text,
        "started_at" timestamp with time zone,
        "completed_at" timestamp with time zone,
        "created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "proposed_tasks" (
        "id" serial PRIMARY KEY NOT NULL,
        "workspace_id" integer,
        "idempotency_key" text,
        "proposed_by" integer,
        "proposed_by_name" text NOT NULL,
        "proposed_by_role" text NOT NULL,
        "platform" text NOT NULL,
        "platform_label" text NOT NULL,
        "tool_name" text NOT NULL,
        "tool_display_name" text NOT NULL,
        "tool_args" jsonb NOT NULL,
        "display_diff" jsonb,
        "reasoning" text DEFAULT '' NOT NULL,
        "snapshot_id" integer,
        "comments" text DEFAULT '' NOT NULL,
        "status" text DEFAULT 'pending' NOT NULL,
        "assigned_to" integer,
        "assigned_to_name" text,
        "resolved_by" integer,
        "resolved_by_name" text,
        "resolved_at" timestamp with time zone,
        "attempt_count" integer DEFAULT 0 NOT NULL,
        "next_retry_at" timestamp with time zone,
        "last_retry_class" text,
        "created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "task_activity_log" (
        "id" serial PRIMARY KEY NOT NULL,
        "task_id" integer NOT NULL,
        "actor_id" integer,
        "actor_name" text NOT NULL,
        "actor_role" text NOT NULL,
        "action" text NOT NULL,
        "note" text DEFAULT '' NOT NULL,
        "target_member_id" integer,
        "target_member_name" text,
        "created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "resolution_library" (
        "id" serial PRIMARY KEY NOT NULL,
        "workspace_id" integer,
        "task_id" integer,
        "saved_by" integer,
        "saved_by_name" text NOT NULL,
        "platform" text NOT NULL,
        "platform_label" text NOT NULL,
        "tool_name" text NOT NULL,
        "tool_display_name" text NOT NULL,
        "tool_args" jsonb NOT NULL,
        "original_problem" text NOT NULL,
        "reasoning" text DEFAULT '' NOT NULL,
        "display_diff" jsonb,
        "tags" jsonb DEFAULT '[]'::jsonb,
        "is_public" boolean DEFAULT true NOT NULL,
        "created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "webhook_threads" (
        "id" serial PRIMARY KEY NOT NULL,
        "alert_id" integer,
        "task_id" integer,
        "thread_key" text NOT NULL,
        "channel_type" text DEFAULT 'teams' NOT NULL,
        "alert_title" text NOT NULL,
        "status" text DEFAULT 'open' NOT NULL,
        "created_at" timestamp with time zone DEFAULT now() NOT NULL,
        "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "shared_reports" (
        "id" serial PRIMARY KEY NOT NULL,
        "share_id" text NOT NULL,
        "workspace_id" integer NOT NULL,
        "agency_name" text,
        "report_title" text DEFAULT 'Performance Report' NOT NULL,
        "report_data" jsonb NOT NULL,
        "expires_at" timestamp with time zone,
        "is_active" boolean DEFAULT true NOT NULL,
        "created_at" timestamp with time zone DEFAULT now() NOT NULL,
        CONSTRAINT "shared_reports_share_id_unique" UNIQUE("share_id")
);
--> statement-breakpoint
CREATE TABLE "saved_reports" (
        "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
        "workspace_id" integer NOT NULL,
        "created_by" integer,
        "definition" jsonb NOT NULL,
        "created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "custom_metrics" (
        "id" serial PRIMARY KEY NOT NULL,
        "organization_id" integer NOT NULL,
        "workspace_id" integer,
        "name" text NOT NULL,
        "description" text,
        "data_type" text DEFAULT 'number' NOT NULL,
        "formula" text NOT NULL,
        "created_by" integer,
        "created_at" timestamp with time zone DEFAULT now() NOT NULL,
        "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "uploaded_datasets" (
        "id" serial PRIMARY KEY NOT NULL,
        "organization_id" integer NOT NULL,
        "workspace_id" integer,
        "name" text NOT NULL,
        "table_name" text NOT NULL,
        "columns" jsonb DEFAULT '[]'::jsonb NOT NULL,
        "row_count" integer DEFAULT 0 NOT NULL,
        "file_size" integer,
        "uploaded_by" integer,
        "created_at" timestamp with time zone DEFAULT now() NOT NULL,
        CONSTRAINT "uploaded_datasets_table_name_unique" UNIQUE("table_name")
);
--> statement-breakpoint
CREATE TABLE "workspace_db_credentials" (
        "id" serial PRIMARY KEY NOT NULL,
        "workspace_id" integer NOT NULL,
        "organization_id" integer NOT NULL,
        "db_type" text NOT NULL,
        "label" text,
        "host" text NOT NULL,
        "port" integer NOT NULL,
        "database_name" text NOT NULL,
        "username" text NOT NULL,
        "encrypted_password" text NOT NULL,
        "service_account_key" text,
        "status" text DEFAULT 'pending' NOT NULL,
        "last_tested_at" timestamp with time zone,
        "created_at" timestamp with time zone DEFAULT now() NOT NULL,
        "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "workspace_financials" (
        "id" serial PRIMARY KEY NOT NULL,
        "workspace_id" integer NOT NULL,
        "month" text NOT NULL,
        "revenue" double precision DEFAULT 0 NOT NULL,
        "cogs" double precision DEFAULT 0 NOT NULL,
        "operating_expenses" double precision DEFAULT 0 NOT NULL,
        "interest_expense" double precision DEFAULT 0 NOT NULL,
        "tax_expense" double precision DEFAULT 0 NOT NULL,
        "notes" text,
        "created_at" timestamp with time zone DEFAULT now() NOT NULL,
        "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "workspace_sales_targets" (
        "id" serial PRIMARY KEY NOT NULL,
        "workspace_id" integer NOT NULL,
        "team_member_id" integer,
        "salesperson_name" text NOT NULL,
        "salesperson_email" text DEFAULT '',
        "sales_target" double precision DEFAULT 0 NOT NULL,
        "closed_amount" double precision DEFAULT 0 NOT NULL,
        "expenses" double precision DEFAULT 0 NOT NULL,
        "status" text DEFAULT 'not_started' NOT NULL,
        "period" text DEFAULT '' NOT NULL,
        "created_at" timestamp with time zone DEFAULT now() NOT NULL,
        "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "agency_ops_tasks" (
        "id" serial PRIMARY KEY NOT NULL,
        "organization_id" integer NOT NULL,
        "title" text NOT NULL,
        "description" text DEFAULT '' NOT NULL,
        "priority" text DEFAULT 'medium' NOT NULL,
        "due_date" timestamp with time zone,
        "status" text DEFAULT 'not_started' NOT NULL,
        "assigned_to" integer,
        "assigned_to_name" text DEFAULT '' NOT NULL,
        "messages_exchanged" integer DEFAULT 0 NOT NULL,
        "avg_response_time_hours" double precision DEFAULT 0 NOT NULL,
        "created_by" integer,
        "created_by_name" text DEFAULT '' NOT NULL,
        "created_at" timestamp with time zone DEFAULT now() NOT NULL,
        "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "leads" (
        "id" serial PRIMARY KEY NOT NULL,
        "source" text DEFAULT 'demo' NOT NULL,
        "email" text NOT NULL,
        "name" text,
        "website" text,
        "company" text,
        "employees" text,
        "revenue_model" text,
        "attribution" text,
        "scheduled_date" text,
        "scheduled_time" text,
        "message" text,
        "status" text DEFAULT 'new' NOT NULL,
        "notes" text,
        "created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "bi_ad_performance" (
        "id" serial PRIMARY KEY NOT NULL,
        "workspace_id" integer,
        "date" text NOT NULL,
        "channel" text NOT NULL,
        "spend" double precision DEFAULT 0 NOT NULL,
        "clicks" integer DEFAULT 0 NOT NULL,
        "conversions" integer DEFAULT 0 NOT NULL,
        "revenue" double precision DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "bi_store_metrics" (
        "id" serial PRIMARY KEY NOT NULL,
        "workspace_id" integer,
        "date" text NOT NULL,
        "total_revenue" double precision DEFAULT 0 NOT NULL,
        "cogs" double precision DEFAULT 0 NOT NULL,
        "shipping_costs" double precision DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "bi_system_logs" (
        "id" serial PRIMARY KEY NOT NULL,
        "workspace_id" integer,
        "type" text DEFAULT 'System Request' NOT NULL,
        "message" text NOT NULL,
        "created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "bi_targets" (
        "id" serial PRIMARY KEY NOT NULL,
        "workspace_id" integer,
        "roas_target" double precision DEFAULT 4 NOT NULL,
        "margin_target" double precision DEFAULT 35 NOT NULL,
        "cpl_cap" double precision DEFAULT 45 NOT NULL,
        CONSTRAINT "bi_targets_workspace_id_unique" UNIQUE("workspace_id")
);
--> statement-breakpoint
CREATE TABLE "ld_ad_performance" (
        "id" serial PRIMARY KEY NOT NULL,
        "workspace_id" integer,
        "date" text NOT NULL,
        "channel" text NOT NULL,
        "spend" double precision DEFAULT 0 NOT NULL,
        "clicks" integer DEFAULT 0 NOT NULL,
        "impressions" integer DEFAULT 0 NOT NULL,
        "form_submissions" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ld_crm_leads" (
        "id" serial PRIMARY KEY NOT NULL,
        "workspace_id" integer,
        "date" text NOT NULL,
        "lead_id" text NOT NULL,
        "lead_status" text DEFAULT 'Raw' NOT NULL,
        "pipeline_value" double precision DEFAULT 0 NOT NULL,
        "channel" text
);
--> statement-breakpoint
CREATE TABLE "ld_system_logs" (
        "id" serial PRIMARY KEY NOT NULL,
        "workspace_id" integer,
        "type" text DEFAULT 'System Request' NOT NULL,
        "message" text NOT NULL,
        "created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ld_targets" (
        "id" serial PRIMARY KEY NOT NULL,
        "workspace_id" integer,
        "cpl_cap" double precision DEFAULT 45 NOT NULL,
        "monthly_lead_target" integer DEFAULT 200 NOT NULL,
        "pipeline_roi_target" double precision DEFAULT 5 NOT NULL,
        CONSTRAINT "ld_targets_workspace_id_unique" UNIQUE("workspace_id")
);
--> statement-breakpoint
CREATE TABLE "hy_ad_performance" (
        "id" serial PRIMARY KEY NOT NULL,
        "workspace_id" integer,
        "date" text NOT NULL,
        "channel" text NOT NULL,
        "campaign_type" text DEFAULT 'ecom' NOT NULL,
        "spend" double precision DEFAULT 0 NOT NULL,
        "clicks" integer DEFAULT 0 NOT NULL,
        "total_conversions" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "hy_crm_leads" (
        "id" serial PRIMARY KEY NOT NULL,
        "workspace_id" integer,
        "date" text NOT NULL,
        "lead_id" text NOT NULL,
        "lead_status" text DEFAULT 'Raw' NOT NULL,
        "estimated_deal_value" double precision DEFAULT 0 NOT NULL,
        "channel" text
);
--> statement-breakpoint
CREATE TABLE "hy_ecom_sales" (
        "id" serial PRIMARY KEY NOT NULL,
        "workspace_id" integer,
        "date" text NOT NULL,
        "order_id" text NOT NULL,
        "revenue" double precision DEFAULT 0 NOT NULL,
        "cogs" double precision DEFAULT 0 NOT NULL,
        "shipping_costs" double precision DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "hy_system_logs" (
        "id" serial PRIMARY KEY NOT NULL,
        "workspace_id" integer,
        "type" text DEFAULT 'System Request' NOT NULL,
        "message" text NOT NULL,
        "created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "hy_targets" (
        "id" serial PRIMARY KEY NOT NULL,
        "workspace_id" integer,
        "roas_goal" double precision DEFAULT 4 NOT NULL,
        "margin_target" double precision DEFAULT 35 NOT NULL,
        "cpl_cap" double precision DEFAULT 45 NOT NULL,
        CONSTRAINT "hy_targets_workspace_id_unique" UNIQUE("workspace_id")
);
--> statement-breakpoint
CREATE TABLE "looker_templates" (
        "id" serial PRIMARY KEY NOT NULL,
        "name" text NOT NULL,
        "looker_dashboard_id" text NOT NULL,
        "category" text DEFAULT 'general' NOT NULL,
        "report_type" text DEFAULT 'interactive' NOT NULL,
        "agency_id" integer,
        "created_at" timestamp with time zone DEFAULT now() NOT NULL,
        "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ai_agents" (
        "id" serial PRIMARY KEY NOT NULL,
        "organization_id" integer NOT NULL,
        "workspace_id" integer,
        "name" text NOT NULL,
        "tone_of_voice" text DEFAULT 'Professional' NOT NULL,
        "objective" text DEFAULT 'Customer Support' NOT NULL,
        "custom_objective" text,
        "system_prompt" text,
        "primary_color" text DEFAULT '#1a73e8' NOT NULL,
        "welcome_message" text DEFAULT 'Hi! How can I help you today?' NOT NULL,
        "script_id" text,
        "is_active" boolean DEFAULT false NOT NULL,
        "stripe_subscription_id" text,
        "stripe_customer_id" text,
        "total_conversations" integer DEFAULT 0 NOT NULL,
        "total_messages" integer DEFAULT 0 NOT NULL,
        "created_at" timestamp DEFAULT now() NOT NULL,
        "updated_at" timestamp DEFAULT now() NOT NULL,
        CONSTRAINT "ai_agents_script_id_unique" UNIQUE("script_id")
);
--> statement-breakpoint
CREATE TABLE "kb_chunks" (
        "id" serial PRIMARY KEY NOT NULL,
        "document_id" integer NOT NULL,
        "agent_id" integer NOT NULL,
        "content" text NOT NULL,
        "embedding" vector(768),
        "metadata" jsonb,
        "created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "kb_documents" (
        "id" serial PRIMARY KEY NOT NULL,
        "agent_id" integer NOT NULL,
        "file_name" text NOT NULL,
        "file_type" text NOT NULL,
        "file_size" integer DEFAULT 0 NOT NULL,
        "status" text DEFAULT 'processing' NOT NULL,
        "chunk_count" integer DEFAULT 0 NOT NULL,
        "error_message" text,
        "created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "promo_triggers" (
        "id" serial PRIMARY KEY NOT NULL,
        "organization_id" integer,
        "product_id" text,
        "product_title" text,
        "sku" text,
        "inventory_qty" integer,
        "avg_poas_7d" numeric(10, 4),
        "discount_percent" integer DEFAULT 15,
        "promo_code" text,
        "shopify_price_rule_id" text,
        "shopify_discount_code_id" text,
        "google_ads_asset_id" text,
        "projected_recovery" numeric(12, 2),
        "status" text DEFAULT 'pending',
        "approved_at" timestamp,
        "rejected_at" timestamp,
        "executed_at" timestamp,
        "error_message" text,
        "triggered_at" timestamp DEFAULT now() NOT NULL,
        "created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "processed_webhook_events" (
        "provider" varchar(32) NOT NULL,
        "event_id" varchar(255) NOT NULL,
        "processed_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "adk_sessions" (
        "id" text PRIMARY KEY NOT NULL,
        "app_name" text NOT NULL,
        "user_id" text NOT NULL,
        "state" jsonb DEFAULT '{}'::jsonb NOT NULL,
        "events" jsonb DEFAULT '[]'::jsonb NOT NULL,
        "title" text,
        "pinned" boolean DEFAULT false NOT NULL,
        "archived_at" timestamp with time zone,
        "created_at" timestamp with time zone DEFAULT now() NOT NULL,
        "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "fx_overrides" (
        "id" serial PRIMARY KEY NOT NULL,
        "workspace_id" integer NOT NULL,
        "base" text DEFAULT 'USD' NOT NULL,
        "quote" text NOT NULL,
        "rate" double precision NOT NULL,
        "note" text,
        "created_at" timestamp DEFAULT now() NOT NULL,
        "updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "fx_rates" (
        "id" serial PRIMARY KEY NOT NULL,
        "base" text DEFAULT 'USD' NOT NULL,
        "quote" text NOT NULL,
        "rate_date" date NOT NULL,
        "rate" double precision NOT NULL,
        "source" text DEFAULT 'exchangerate.host' NOT NULL,
        "fetched_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "saved_views" (
        "id" serial PRIMARY KEY NOT NULL,
        "workspace_id" integer NOT NULL,
        "user_id" text NOT NULL,
        "page_key" text NOT NULL,
        "name" text NOT NULL,
        "filters" jsonb NOT NULL,
        "date_preset" text,
        "custom_from" text,
        "custom_to" text,
        "created_at" timestamp with time zone DEFAULT now() NOT NULL,
        "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "product_feedgen_rewrites" (
        "id" text PRIMARY KEY NOT NULL,
        "tenant_id" text DEFAULT 'default' NOT NULL,
        "product_id" text NOT NULL,
        "sku" text DEFAULT '' NOT NULL,
        "original_title" text DEFAULT '' NOT NULL,
        "original_description" text DEFAULT '' NOT NULL,
        "rewritten_title" text DEFAULT '' NOT NULL,
        "rewritten_description" text DEFAULT '' NOT NULL,
        "quality_score" integer DEFAULT 0 NOT NULL,
        "reasoning" text DEFAULT '' NOT NULL,
        "cited_attributes" jsonb DEFAULT '[]'::jsonb NOT NULL,
        "trigger_signals" jsonb DEFAULT 'null'::jsonb,
        "status" text DEFAULT 'pending' NOT NULL,
        "approved_task_id" integer,
        "error_code" text,
        "error_message" text,
        "latency_ms" double precision DEFAULT 0,
        "generated_at" timestamp with time zone DEFAULT now() NOT NULL,
        "approved_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "feedgen_runs" (
        "id" serial PRIMARY KEY NOT NULL,
        "tenant_id" text DEFAULT 'default' NOT NULL,
        "mode" text DEFAULT 'underperformer' NOT NULL,
        "status" text DEFAULT 'completed' NOT NULL,
        "skip_reason" text,
        "scanned" integer DEFAULT 0 NOT NULL,
        "generated" integer DEFAULT 0 NOT NULL,
        "failed" integer DEFAULT 0 NOT NULL,
        "prompt_tokens" bigint DEFAULT 0 NOT NULL,
        "candidates_tokens" bigint DEFAULT 0 NOT NULL,
        "total_tokens" bigint DEFAULT 0 NOT NULL,
        "median_roas" double precision,
        "started_at" timestamp with time zone DEFAULT now() NOT NULL,
        "finished_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ai_gads_daily_usage" (
        "id" serial PRIMARY KEY NOT NULL,
        "organization_id" integer NOT NULL,
        "usage_date" date NOT NULL,
        "rows_read" integer DEFAULT 0 NOT NULL,
        "query_count" integer DEFAULT 0 NOT NULL,
        "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "messages" ADD CONSTRAINT "messages_conversation_id_conversations_id_fk" FOREIGN KEY ("conversation_id") REFERENCES "public"."conversations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "state_snapshots" ADD CONSTRAINT "state_snapshots_conversation_id_conversations_id_fk" FOREIGN KEY ("conversation_id") REFERENCES "public"."conversations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "audit_logs" ADD CONSTRAINT "audit_logs_conversation_id_conversations_id_fk" FOREIGN KEY ("conversation_id") REFERENCES "public"."conversations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "audit_logs" ADD CONSTRAINT "audit_logs_snapshot_id_state_snapshots_id_fk" FOREIGN KEY ("snapshot_id") REFERENCES "public"."state_snapshots"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "campaign_targets" ADD CONSTRAINT "campaign_targets_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "workspaces" ADD CONSTRAINT "workspaces_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "proposed_tasks" ADD CONSTRAINT "proposed_tasks_proposed_by_team_members_id_fk" FOREIGN KEY ("proposed_by") REFERENCES "public"."team_members"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "proposed_tasks" ADD CONSTRAINT "proposed_tasks_assigned_to_team_members_id_fk" FOREIGN KEY ("assigned_to") REFERENCES "public"."team_members"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "proposed_tasks" ADD CONSTRAINT "proposed_tasks_resolved_by_team_members_id_fk" FOREIGN KEY ("resolved_by") REFERENCES "public"."team_members"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "task_activity_log" ADD CONSTRAINT "task_activity_log_task_id_proposed_tasks_id_fk" FOREIGN KEY ("task_id") REFERENCES "public"."proposed_tasks"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "task_activity_log" ADD CONSTRAINT "task_activity_log_actor_id_team_members_id_fk" FOREIGN KEY ("actor_id") REFERENCES "public"."team_members"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "task_activity_log" ADD CONSTRAINT "task_activity_log_target_member_id_team_members_id_fk" FOREIGN KEY ("target_member_id") REFERENCES "public"."team_members"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "resolution_library" ADD CONSTRAINT "resolution_library_task_id_proposed_tasks_id_fk" FOREIGN KEY ("task_id") REFERENCES "public"."proposed_tasks"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "resolution_library" ADD CONSTRAINT "resolution_library_saved_by_team_members_id_fk" FOREIGN KEY ("saved_by") REFERENCES "public"."team_members"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "bi_ad_performance" ADD CONSTRAINT "bi_ad_performance_workspace_id_workspaces_id_fk" FOREIGN KEY ("workspace_id") REFERENCES "public"."workspaces"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "bi_store_metrics" ADD CONSTRAINT "bi_store_metrics_workspace_id_workspaces_id_fk" FOREIGN KEY ("workspace_id") REFERENCES "public"."workspaces"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "bi_system_logs" ADD CONSTRAINT "bi_system_logs_workspace_id_workspaces_id_fk" FOREIGN KEY ("workspace_id") REFERENCES "public"."workspaces"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "bi_targets" ADD CONSTRAINT "bi_targets_workspace_id_workspaces_id_fk" FOREIGN KEY ("workspace_id") REFERENCES "public"."workspaces"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ld_ad_performance" ADD CONSTRAINT "ld_ad_performance_workspace_id_workspaces_id_fk" FOREIGN KEY ("workspace_id") REFERENCES "public"."workspaces"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ld_crm_leads" ADD CONSTRAINT "ld_crm_leads_workspace_id_workspaces_id_fk" FOREIGN KEY ("workspace_id") REFERENCES "public"."workspaces"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ld_system_logs" ADD CONSTRAINT "ld_system_logs_workspace_id_workspaces_id_fk" FOREIGN KEY ("workspace_id") REFERENCES "public"."workspaces"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ld_targets" ADD CONSTRAINT "ld_targets_workspace_id_workspaces_id_fk" FOREIGN KEY ("workspace_id") REFERENCES "public"."workspaces"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "hy_ad_performance" ADD CONSTRAINT "hy_ad_performance_workspace_id_workspaces_id_fk" FOREIGN KEY ("workspace_id") REFERENCES "public"."workspaces"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "hy_crm_leads" ADD CONSTRAINT "hy_crm_leads_workspace_id_workspaces_id_fk" FOREIGN KEY ("workspace_id") REFERENCES "public"."workspaces"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "hy_ecom_sales" ADD CONSTRAINT "hy_ecom_sales_workspace_id_workspaces_id_fk" FOREIGN KEY ("workspace_id") REFERENCES "public"."workspaces"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "hy_system_logs" ADD CONSTRAINT "hy_system_logs_workspace_id_workspaces_id_fk" FOREIGN KEY ("workspace_id") REFERENCES "public"."workspaces"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "hy_targets" ADD CONSTRAINT "hy_targets_workspace_id_workspaces_id_fk" FOREIGN KEY ("workspace_id") REFERENCES "public"."workspaces"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ai_gads_daily_usage" ADD CONSTRAINT "ai_gads_daily_usage_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "conversations_org_id_idx" ON "conversations" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "conversations_user_id_idx" ON "conversations" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_messages_conversation_id" ON "messages" USING btree ("conversation_id");--> statement-breakpoint
CREATE INDEX "platform_connections_org_id_idx" ON "platform_connections" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "platform_connections_platform_idx" ON "platform_connections" USING btree ("platform");--> statement-breakpoint
CREATE INDEX "audit_logs_org_id_idx" ON "audit_logs" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "audit_logs_created_at_idx" ON "audit_logs" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "audit_logs_insight_id_idx" ON "audit_logs" USING btree ("insight_id");--> statement-breakpoint
CREATE INDEX "product_quality_fixes_tenant_idx" ON "product_quality_fixes" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "product_quality_fixes_change_count_idx" ON "product_quality_fixes" USING btree ("change_count");--> statement-breakpoint
CREATE UNIQUE INDEX "crm_leads_provider_id_uidx" ON "warehouse_crm_leads" USING btree ("crm_provider","crm_lead_id");--> statement-breakpoint
CREATE UNIQUE INDEX "cross_platform_mapping_ad_product_uidx" ON "warehouse_cross_platform_mapping" USING btree ("google_ad_id","shopify_product_id");--> statement-breakpoint
CREATE INDEX "warehouse_google_ads_tenant_idx" ON "warehouse_google_ads" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "warehouse_google_ads_campaign_idx" ON "warehouse_google_ads" USING btree ("campaign_id");--> statement-breakpoint
CREATE INDEX "warehouse_google_ads_asset_groups_tenant_idx" ON "warehouse_google_ads_asset_groups" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "warehouse_google_ads_asset_groups_campaign_idx" ON "warehouse_google_ads_asset_groups" USING btree ("campaign_id");--> statement-breakpoint
CREATE INDEX "warehouse_shopify_products_tenant_idx" ON "warehouse_shopify_products" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "team_members_org_id_idx" ON "team_members" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "team_members_email_idx" ON "team_members" USING btree ("email");--> statement-breakpoint
CREATE INDEX "team_members_workspace_id_idx" ON "team_members" USING btree ("workspace_id");--> statement-breakpoint
CREATE UNIQUE INDEX "campaign_targets_org_campaign_uq" ON "campaign_targets" USING btree ("organization_id","campaign_id");--> statement-breakpoint
CREATE INDEX "campaign_targets_org_idx" ON "campaign_targets" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "feed_enrichment_jobs_org_idx" ON "feed_enrichment_jobs" USING btree ("organization_id");--> statement-breakpoint
CREATE UNIQUE INDEX "uq_proposed_tasks_idempotency" ON "proposed_tasks" USING btree ("idempotency_key");--> statement-breakpoint
CREATE INDEX "saved_reports_workspace_idx" ON "saved_reports" USING btree ("workspace_id");--> statement-breakpoint
CREATE UNIQUE INDEX "workspace_financials_ws_month_uidx" ON "workspace_financials" USING btree ("workspace_id","month");--> statement-breakpoint
CREATE INDEX "workspace_financials_ws_idx" ON "workspace_financials" USING btree ("workspace_id");--> statement-breakpoint
CREATE INDEX "workspace_sales_targets_ws_idx" ON "workspace_sales_targets" USING btree ("workspace_id");--> statement-breakpoint
CREATE INDEX "workspace_sales_targets_period_idx" ON "workspace_sales_targets" USING btree ("workspace_id","period");--> statement-breakpoint
CREATE INDEX "agency_ops_tasks_org_idx" ON "agency_ops_tasks" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "agency_ops_tasks_status_idx" ON "agency_ops_tasks" USING btree ("organization_id","status");--> statement-breakpoint
CREATE INDEX "agency_ops_tasks_priority_idx" ON "agency_ops_tasks" USING btree ("organization_id","priority");--> statement-breakpoint
CREATE INDEX "leads_status_idx" ON "leads" USING btree ("status");--> statement-breakpoint
CREATE INDEX "leads_created_at_idx" ON "leads" USING btree ("created_at");--> statement-breakpoint
CREATE UNIQUE INDEX "bi_adperf_uniq" ON "bi_ad_performance" USING btree ("workspace_id","date","channel");--> statement-breakpoint
CREATE UNIQUE INDEX "bi_store_uniq" ON "bi_store_metrics" USING btree ("workspace_id","date");--> statement-breakpoint
CREATE UNIQUE INDEX "ld_adperf_uniq" ON "ld_ad_performance" USING btree ("workspace_id","date","channel");--> statement-breakpoint
CREATE UNIQUE INDEX "hy_adperf_uniq" ON "hy_ad_performance" USING btree ("workspace_id","date","channel","campaign_type");--> statement-breakpoint
CREATE UNIQUE INDEX "processed_webhook_events_provider_event_id_idx" ON "processed_webhook_events" USING btree ("provider","event_id");--> statement-breakpoint
CREATE INDEX "adk_sessions_app_user_idx" ON "adk_sessions" USING btree ("app_name","user_id");--> statement-breakpoint
CREATE INDEX "adk_sessions_updated_at_idx" ON "adk_sessions" USING btree ("updated_at");--> statement-breakpoint
CREATE INDEX "adk_sessions_pinned_idx" ON "adk_sessions" USING btree ("pinned");--> statement-breakpoint
CREATE INDEX "adk_sessions_archived_idx" ON "adk_sessions" USING btree ("archived_at");--> statement-breakpoint
CREATE UNIQUE INDEX "fx_overrides_ws_base_quote_idx" ON "fx_overrides" USING btree ("workspace_id","base","quote");--> statement-breakpoint
CREATE UNIQUE INDEX "fx_rates_base_quote_date_idx" ON "fx_rates" USING btree ("base","quote","rate_date");--> statement-breakpoint
CREATE INDEX "fx_rates_quote_date_idx" ON "fx_rates" USING btree ("quote","rate_date");--> statement-breakpoint
CREATE UNIQUE INDEX "saved_views_user_page_name_uq" ON "saved_views" USING btree ("workspace_id","user_id","page_key","name");--> statement-breakpoint
CREATE INDEX "product_feedgen_rewrites_tenant_idx" ON "product_feedgen_rewrites" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "product_feedgen_rewrites_status_idx" ON "product_feedgen_rewrites" USING btree ("status");--> statement-breakpoint
CREATE INDEX "product_feedgen_rewrites_score_idx" ON "product_feedgen_rewrites" USING btree ("quality_score");--> statement-breakpoint
CREATE UNIQUE INDEX "product_feedgen_rewrites_pk_uidx" ON "product_feedgen_rewrites" USING btree ("id");--> statement-breakpoint
CREATE INDEX "feedgen_runs_tenant_idx" ON "feedgen_runs" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "feedgen_runs_started_at_idx" ON "feedgen_runs" USING btree ("started_at");--> statement-breakpoint
CREATE INDEX "ai_gads_usage_org_date_idx" ON "ai_gads_daily_usage" USING btree ("organization_id","usage_date");